### ISSUE TITLE
Decide if client.min.js really belongs in repo

### ISSUE THREAD

**Issue by tony-johnson** [lsst-camera-visualization/lsst-vis#22]
My feeling is that this is a generated file, not a source file, and should not be in the repo, since it is likely to cause conflicts on each pull. If we get rid of it the installation instructions need to be updated.

**Comment by weiren2** [comment]
Then we should remove client.min.js. Plus it also helps reducing the size of git history.

**Comment by weiren2** [comment]
I removed client.min.js from the reop. Please pull or start with fresh clone before committing new changes.
