### ISSUE TITLE
Support file:/path/to/file as well as file:///path/to/file

### ISSUE THREAD

**Issue by tony-johnson** [lsst-camera-visualization/lsst-vis#23]
The current ingest server returns URLs of the form file:/path/to/file so we need to support that.

**Comment by tony-johnson** [comment]
Wei has found a fix for the ingest server by using Path.toUri() instead of File.toUri() so we will try that instead.

**Comment by weiren2** [comment]
Path.toUri() is using RFC standards while File.toURI() is not (see <https://stackoverflow.com/a/17870390>)

Commit in ingest server: lsst-camera-visualization/visualization-server@faaa7fe

**Comment by tony-johnson** [comment]
No need to fix this since handled in ingestServer
